// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/telugu-game/TeluguWordGame.tsx": () => import("../components/mockups/telugu-game/TeluguWordGame.tsx")
};
